# DataFrame class

In [1]:
import numpy as np
import pandas as pd

## 생성

In [2]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [3]:
df.지역.values

array(['수도권', '경상권', '수도권', '경상권'], dtype=object)

In [4]:
df['2015'].values

array([9904312, 3448737, 2890451, 2466052])

In [5]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [6]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [ ]:
# 전치
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

### 열 데이터의 갱신, 추가, 삭제

In [ ]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [ ]:
# 열 추가 
df['2020'] = [1,2,3,4]
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [ ]:
# 삭제, 지우기
del df['2020']
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

### 열 인덱싱

In [ ]:
# 결과는 Series로 출력된다 
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [ ]:
# 결과는 dataframe [[column]]안에서 출력 
df[['지역', '2015']]

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [ ]:
# type의 종류도 다양
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

### 행 인덱싱

In [ ]:
df[: '서울']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83

In [ ]:
df[1:2]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63

In [ ]:
df['부산':'인천']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [ ]:
df.head(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

## 개별 데이터 인덱싱
- df ['열 이름']['행 이름']

In [ ]:
df['2015']['서울'], df['2015'][0]

(9904312, 9904312)

### 연습 문제 4.1.3

In [8]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [9]:
# 1) 수학 점수를 시리즈로
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [10]:
# 2) 국어, 영어 점수를 데이터프레임으로
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [ ]:
# 3) 평균을 새로운 열로 추가
# df 에서 value를 출력한다 - array
df.values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]])

In [ ]:
# numpy 방법을 사용하여 평균값을 구하라 
np.mean(df.values, axis=1).round(1)

array([86.7, 73.3, 70. , 46.7])

In [ ]:
df['평균']=np.mean(df.values, axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [ ]:
df.mean(axis=1)

춘향    86.675
몽룡    73.325
향단    70.000
방자    46.675
dtype: float64

In [ ]:
# 4) 방자 영어점수를 80점으로 수정
del df['평균']
df['영어']['방자'] = 80
df['평균']= np.mean(df.values, axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [ ]:
# 5) 춘향의 점수를 데이터프레임으로
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df.head(1)

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df.T[['춘향']]

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

In [ ]:
 # 가운데 값을 출력하는 경우
 df.head(3).tail(2)

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

In [11]:
# 6) 향단의 점수를 시리즈로
df.T['향단']

국어    70
영어    60
수학    80
Name: 향단, dtype: int64