### Numpy를 활용한 벡터,행렬 연산 
- 참고자료 : [데이터사이언스스쿨](http://datascienceschool.net/intro.html)

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris

iris = load_iris()
iris.data[0, :]

array([5.1, 3.5, 1.4, 0.2])

* 연습문제 2.1.1 

In [8]:
# 2차원 백터로 표현하기
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [11]:
 # 행렬 변수 x 만들기 
 x = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
 x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [12]:
# 전치행렬
x.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [13]:
# 전치행렬 2번 
(x.T).T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [16]:
# 영백터 = np.zeros()

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
# 1백터
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
# 대각 행렬 
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
# 항등행렬(identity matrix)

np.eye(2)

array([[1., 0.],
       [0., 1.]])

* 연습문제 2.2.1

In [25]:
p = np.array([[100], [80], [50]])
n = np.array([[3], [4], [5]])

In [30]:
# 내적(inner product)

p.T@n

array([[870]])

In [31]:
# dot product
np.dot(p.T, n)

array([[870]])

* 연습문제 2.2.3

In [34]:
from sklearn.datasets import load_digits
X = load_digits().data
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [40]:
# 첫번째 이미자와 10번째 이미지의 유사도 구하기
X[0, :] @ X[9, :]

2807.0