# Numerical Python(Numpy)-Part1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [3]:
a= [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x : 3*x, a))

[3, 6, 9]

In [6]:
b= np.array([1,2,3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [8]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [9]:
type(a)

numpy.ndarray

In [10]:
# shape = 몇 차원? / 튜플로 표현함 

a.dtype,a.shape

(dtype('float64'), (4,))

## 2. Array Shape

In [21]:
# Vector (1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [17]:
# Matrix (2차원)
matrix= np.array([[1,2,3,], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [18]:
# Tensor (3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [25]:
# element의 갯수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [38]:
# data type
# float 32 : 32bit로 표시 - single precision 
# float 64 : 64bit로 표시 - double precision

a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [33]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [35]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [36]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
# -1은 numpy가 알아서 맞춰줌(단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [45]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [41]:
matrix.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
tensor.reshape(4,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

### flatten

In [55]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [56]:
# 다 차원 array를 1차원 arry로 변환
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3.Indexing

In [52]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
matrix[0,1]

2

In [57]:
tensor[1,1,2]

19

### slicing

In [59]:
b= np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
#5,6,9,20
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [63]:
# 5,6,7,9,10,11
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [65]:
# 1, 3, 9, 11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [66]:
# X는 앞에 3열, y는 마지막 열 

X,y = b[:,:-1],b[:,-1]
X.shape, y.shape

((4, 3), (4,))