### 1. 프리미어리그 데이터 상관계수 분석
- 2016년 프리미어리그 성적에서 득점과 실점 데이터중에 승점에 영향을 더 많이 준 데이터는?

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("premierleague.csv")
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [7]:
# 득점
gf= np.array(df['gf'])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31])

In [8]:
# 실점 
ga = np.array(df['ga'])
ga

array([27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
       56, 68, 56])

In [9]:
# 승점
points =np.array(df['points'])
points

array([100,  81,  77,  75,  70,  63,  54,  49,  47,  44,  44,  44,  42,
        41,  40,  37,  36,  33,  33,  31])

In [11]:
data1, data2 = np.corrcoef(gf, points)[0,1] ** 2, np.corrcoef(ga, points)[0,1] ** 2
(data1,data2)

(0.8683266496886471, 0.757933920368845)

In [13]:
round(data1, 2), round(data2, 2)

(0.87, 0.76)

결과 : 득점 데이터가 승점에 큰 영향이 있으므로 공격을 활발하게 하여 득점해야한다 
