데이터 사이언스 온라인 완주반 5기 : 패스트 캠퍼스

In [1]:
from google.colab import files
uploaded= files.upload()
filename= list(uploaded.keys())[0]
filename

Saving premierleague.csv to premierleague.csv


'premierleague.csv'

# 선형회귀 분석 (Linear Regression)
* 프리미어리그 데이터(득점, 실점, 승점)
* 득점, 실점 -> 승점 예측하는 모델
* scikit-learn 패키지
  - 데이터 마이닝 및 데이터 분석, 모델을 위한 도구
  - 상업적으로 사용이 가능한 오픈소스

In [4]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 선형회귀 모델
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

#### 분석 절차
- 데이터 로드
- 데이터 전처리
    - 독립변수와 종속변수를 나눠줌
    - 학습 데이터와 테스트 데이터를 나눠줌
- 데이터 분석 : 선형회귀 모델
- 성능평가 : MAE
- 예측 코드 작성

In [5]:
df = pd.read_csv('premierleague.csv')
df.head()

name   gf  ga  points
0    Manchester City  106  27     100
1  Manchester United   68  28      81
2  Tottenham Hotspur   74  36      77
3          Liverpool   84  38      75
4            Chelsea   62  38      70

In [7]:
# 1. 데이터 전처리: 독립변수(x), 종속변수(y) 나누기

df_x= df[['gf', 'ga']]
df_y =df[['points']]

In [14]:
# 2. 데이터 전처리: 학습 데이터와 테스트 데이터로 나누기 (train, test)
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.3, 
                                                    random_state =1)

In [15]:
# 3. 데이터 분석 : 선형 회귀 모델
model = linear_model.LinearRegression()         # 객체 생성
model.fit(train_x, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
# 4. 성능 평가 :  MAE 
pred_y = model.predict(test_x,)
pred_y      # 예측값

array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [19]:
# 실제 데이터 
test_y['points'].values

array([75, 36, 54, 44, 77, 40])

In [21]:
# 차원 축소 및  실제 데이터와 같은 타입으로 만든다
pred_y = np.around(pred_y.flatten()).astype(int)
pred_y

array([81, 41, 51, 46, 76, 40])

In [23]:
# 오차 범위, 평가 
mae = mean_absolute_error(test_y, pred_y)
mae

2.8333333333333335

In [24]:
# 5. 예측 함수

def make_df(gf, ga):
  return pd.DataFrame({'gf': [gf], 'ga':[ga]})

In [28]:
gf, ga = 80, 30
result = int(model.predict(make_df(gf, ga)).flatten()[0])
result

83